apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: authenticationservice
  name: authenticationservicesvc
spec:
  type: NodePort
  ports:
  - name: "8091"
    port: 8091
  selector:
    name: authenticationservice
status:
  loadBalancer: {}
