apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  labels:
    name: authenticationservice
  name: authenticationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: authenticationservice
  template:
    metadata:
      labels:
        name: authenticationservice
    spec:
      containers:
      - image: shubh1254/authenticationservice:latest
        name: authentication-service-container
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://mysqlservicesvc:3306/AuthenticationDB
        ports:
        - containerPort: 8091
        resources: {}
      restartPolicy: Always
status: {}
