apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: configserver
  name: configserversvc
spec:
  type: NodePort
  ports:
  - name: "8888"
    port: 8888
  selector:
    name: configserver
status:
  loadBalancer: {}
