apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  labels:
    name: emailservice
  name: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: emailservice
  template:
    metadata:
      labels:
        name: emailservice
    spec:
      containers:
      - image: shubh1254/emailservice:latest
        name: email-service-container
        env:
        - name: spring.rabbitmq.host
          value: rabbitmqsvc
        ports:
        - containerPort: 8088
        resources: {}
      restartPolicy: Always
status: {}
