apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: emailservice
  name: emailservicesvc
spec:
  type: NodePort
  ports:
  - name: "8088"
    port: 8088
  selector:
    name: emailservice
status:
  loadBalancer: {}
