apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: mongodbservice
  name: mongodbservicesvc
spec:
  type: NodePort
  ports:
  - name: "27017"
    port: 27017
  selector:
    name: mongodbservice
status:
  loadBalancer: {}
