apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: mysqlservice
  name: mysqlservicesvc
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
  selector:
    name: mysqlservice
status:
  loadBalancer: {}
