apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: paymentservice
  name: paymentservicesvc
spec:
  type: NodePort
  ports:
  - name: "8089"
    port: 8089
  selector:
    name: paymentservice
status:
  loadBalancer: {}
