apiVersion: v1
kind: Service
metadata:
  
  namespace: capstone
  labels:
    name: userservice
  name: userservicesvc
spec:
  type: NodePort
  ports:
  - name: "8083"
    port: 8083
    nodePort: 30048
  selector:
    name: userservice
status:
  loadBalancer: {}
